# Online Reatil Sales Case Study

# Problem Statement
# You are working as a data analyst for an e-commerce company. Management wants insights into sales trends, customer behavior, product performance, and potential revenue issues to improve business decisions.

# You have been provided with a dataset named online_retail_sales.csv, which contains detailed records of customer orders.

In [1]:
# Importing Libraries 
import pandas as pd
import matplotlib.pyplot as pyp
import seaborn as sns

# 1. Data Exploration and Cleaning

In [2]:
# Load the dataset into a Pandas DataFrame and display the first 5 rows.

data = pd.read_csv("online_retail_sales_Large.csv")
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23

In [3]:
# Check the dataset shape, column names, data types, and summary statistics.

print("Shape of Dataset \n", data.shape)
print("Columns Name \n", data.columns.to_list())
print("Data Type of Dataset \n", data.dtypes)
print("Summary Statistics \n", data.describe(include="all"))

Shape of Dataset
 (50000, 11)
Columns Name
 ['Order_ID', 'Customer_ID', 'Order_Date', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Payment_Method', 'Order_Status', 'City', 'Total_Amount']
Data Type of Dataset
 Order_ID            int64
Customer_ID         int64
Order_Date         object
Product            object
Category           object
Quantity            int64
Unit_Price        float64
Payment_Method     object
Order_Status       object
City               object
Total_Amount      float64
dtype: object
Summary Statistics
             Order_ID   Customer_ID  Order_Date Product     Category  \
count   50000.000000  50000.000000       50000   50000        50000
unique           NaN           NaN         731       8            4
top              NaN           NaN  2023-11-11   Watch  Accessories
freq             NaN           NaN          93    6334        12655
mean    25000.500000   5494.083720         NaN     NaN          NaN
std     14433.901067   2601.545347         NaN     NaN          NaN
min         1.000000   1000.000000         NaN     NaN          NaN
25%     12500.750000   3232.750000         NaN     NaN          NaN
50%     25000.500000   5497.000000         NaN     NaN          NaN
75%     37500.250000   7746.000000         NaN     NaN          NaN
max     50000.000000   9999.000000         NaN     NaN          NaN

            Quantity    Unit_Price Payment_Method Order_Status     City  \
count   50000.000000  50000.000000          50000        50000    50000
unique           NaN           NaN              5            3        7
top              NaN           NaN            UPI    Completed  Kolkata
freq             NaN           NaN          10133        37528     7226
mean       12.493440   1259.940694            NaN          NaN      NaN
std         6.901944    715.936278            NaN          NaN      NaN
min         1.000000     20.010000            NaN          NaN      NaN
25%         6.000000    639.095000            NaN          NaN      NaN
50%        13.000000   1261.480000            NaN          NaN      NaN
75%        18.000000   1876.660000            NaN          NaN      NaN
max        24.000000   2499.960000            NaN          NaN      NaN

        Total_Amount
count   50000.000000
unique           NaN
top              NaN
freq             NaN
mean    15776.022701
std     13461.642349
min        22.340000
25%      4619.632500
50%     11949.390000
75%     23997.630000
max     59958.960000

In [4]:
# Identify missing values in each column.

print(data.isnull().sum())

Order_ID          0
Customer_ID       0
Order_Date        0
Product           0
Category          0
Quantity          0
Unit_Price        0
Payment_Method    0
Order_Status      0
City              0
Total_Amount      0
dtype: int64

In [5]:
# Handle missing values appropriately:
# Numerical columns: fill with mean or median.
# Categorical columns: fill with mode or drop.

In [6]:
# Convert Order_Date into datetime format.

data["Order_Date"] = pd.to_datetime(data["Order_Date"])

In [7]:
# Extract Year, Month, and Day from Order_Date into new columns.

data["Order_Date_Day"] = data["Order_Date"].dt.day
data["Order_Date_Month"] = data["Order_Date"].dt.month
data["Order_Date_MonthName"] = data["Order_Date"].dt.month_name()
data["Order_Date_Year"] = data["Order_Date"].dt.year

In [8]:
data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,Total_Amount,Order_Date_Day,Order_Date_Month,Order_Date_MonthName,Order_Date_Year
0,1,8270,2023-09-10,Headphones,Home Appliances,11,582.55,Cash,Completed,Hyderabad,6408.05,10,9,September,2023
1,2,1860,2023-03-14,Laptop,Accessories,8,1635.00,PayPal,Completed,Hyderabad,13080.00,14,3,March,2023
2,3,6390,2023-08-02,Headphones,Electronics,6,877.67,UPI,Completed,Pune,5266.02,2,8,August,2023
3,4,6191,2024-01-14,TV,Accessories,9,2237.20,Credit Card,Completed,Pune,20134.80,14,1,January,2024
4,5,6734,2023-10-26,Laptop,Accessories,7,1359.89,Credit Card,Completed,Mumbai,9519.23,26,10,October,2023

In [9]:
print(data.dtypes)

Order_ID                         int64
Customer_ID                      int64
Order_Date              datetime64[ns]
Product                         object
Category                        object
Quantity                         int64
Unit_Price                     float64
Payment_Method                  object
Order_Status                    object
City                            object
Total_Amount                   float64
Order_Date_Day                   int32
Order_Date_Month                 int32
Order_Date_MonthName            object
Order_Date_Year                  int32
dtype: object

# 2. Data Selection and Filtering

In [10]:
# Retrieve all orders placed in March 2024.

Orders_2024 = data[(data["Order_Date_Year"] == 2024) & (data["Order_Date_Month"] == 3)]
print(Orders_2024.count())

Order_ID                2098
Customer_ID             2098
Order_Date              2098
Product                 2098
Category                2098
Quantity                2098
Unit_Price              2098
Payment_Method          2098
Order_Status            2098
City                    2098
Total_Amount            2098
Order_Date_Day          2098
Order_Date_Month        2098
Order_Date_MonthName    2098
Order_Date_Year         2098
dtype: int64

In [11]:
# Find all orders where: Total_Amount > 1000 & Category is Electronics.

Electronics_Orders_Above1000 = data[(data["Total_Amount"] > 1000) & (data["Category"] == "Electronics")]
print(Electronics_Orders_Above1000.count())

Order_ID                11761
Customer_ID             11761
Order_Date              11761
Product                 11761
Category                11761
Quantity                11761
Unit_Price              11761
Payment_Method          11761
Order_Status            11761
City                    11761
Total_Amount            11761
Order_Date_Day          11761
Order_Date_Month        11761
Order_Date_MonthName    11761
Order_Date_Year         11761
dtype: int64

In [12]:
# Select only Completed orders.

Completed_Orders = data[(data["Order_Status"] == "Completed")]
print(Completed_Orders.count())

Order_ID                37528
Customer_ID             37528
Order_Date              37528
Product                 37528
Category                37528
Quantity                37528
Unit_Price              37528
Payment_Method          37528
Order_Status            37528
City                    37528
Total_Amount            37528
Order_Date_Day          37528
Order_Date_Month        37528
Order_Date_MonthName    37528
Order_Date_Year         37528
dtype: int64

In [13]:
# Retrieve orders placed from Mumbai or Delhi.

Order_Mumbai_Delhi = data[(data["City"] == "Mumbai") | (data["City"] == "Delhi")]
print(Order_Mumbai_Delhi.count())

Order_ID                14282
Customer_ID             14282
Order_Date              14282
Product                 14282
Category                14282
Quantity                14282
Unit_Price              14282
Payment_Method          14282
Order_Status            14282
City                    14282
Total_Amount            14282
Order_Date_Day          14282
Order_Date_Month        14282
Order_Date_MonthName    14282
Order_Date_Year         14282
dtype: int64

# 3. Data Manipulation and Feature Engineering

In [14]:
# Create a new column Discounted_Amount:
# Apply a 10 percent discount on orders where Total_Amount > 8000.

data["Discounted_Amount"] = data["Total_Amount"].apply(lambda x: x * 0.90 if x>8000 else x)

In [15]:
# Create a column Price_Level based on Total_Amount:
# Low: Below 2000
# Medium: 2000 to 8000
# High: Above 8000

data["Price_Level"] = pd.cut(
    data["Total_Amount"],
    bins=[-float("inf"),2000,8000,float("inf")],
    labels=["Low","Medium","High"])
data[["Total_Amount","Discounted_Amount","Price_Level"]].head()

   Total_Amount  Discounted_Amount Price_Level
0       6408.05           6408.050      Medium
1      13080.00          11772.000        High
2       5266.02           5266.020      Medium
3      20134.80          18121.320        High
4       9519.23           8567.307        High

In [16]:
# Create a new column Revenue_Per_Item:
# Revenue_Per_Item = Total_Amount / Quantity

data["Revenue_Per_Item"] = data["Total_Amount"] / data["Quantity"]
data[["Total_Amount","Quantity","Revenue_Per_Item"]].head()

   Total_Amount  Quantity  Revenue_Per_Item
0       6408.05        11            582.55
1      13080.00         8           1635.00
2       5266.02         6            877.67
3      20134.80         9           2237.20
4       9519.23         7           1359.89

In [17]:
# Drop the Product column if more than 40 percent of values are missing.

# 4. Aggregation and Business Insights

In [28]:
# Find the total revenue per Category.

revenue_per_category = data.groupby("Category")["Revenue_Per_Item"].sum().reset_index()
revenue_per_category.head()

          Category  Revenue_Per_Item
0      Accessories       16007919.17
1         Clothing       15798139.79
2      Electronics       15602521.94
3  Home Appliances       15588453.80

In [31]:
# Calculate the average order value per Payment_Method.

average_order = data.groupby("Payment_Method")["Total_Amount"].mean().reset_index()
average_order

  Payment_Method  Total_Amount
0           Cash  15715.246761
1    Credit Card  15755.694077
2     Debit Card  15708.867117
3         PayPal  15985.051394
4            UPI  15718.485191

In [53]:
# Identify the top 5 cities by total sales.

Top5_City = data.groupby("City")["Revenue_Per_Item"].sum().reset_index().sort_values("Revenue_Per_Item", ascending=False).head(5)
Top5_City

      City  Revenue_Per_Item
4  Kolkata        9096816.14
2    Delhi        9067674.90
1  Chennai        9015883.49
5   Mumbai        8996841.09
6     Pune        8979691.48

In [49]:
# Find the number of cancelled and returned orders per Category.

cancelled_returned_orders = data[data["Order_Status"].isin(["Cancelled", "Returned"])].groupby("Category").size().reset_index(name="Count")
cancelled_returned_orders

          Category  Count
0      Accessories   3218
1         Clothing   3117
2      Electronics   3111
3  Home Appliances   3026

In [48]:
# Determine the monthly sales trend.

monthly_sales_trend = data.groupby(["Order_Date_Month", "Order_Date_MonthName"])["Revenue_Per_Item"].sum().reset_index()
monthly_sales_trend

    Order_Date_Month Order_Date_MonthName  Revenue_Per_Item
0                  1              January        5412935.97
1                  2             February        4796702.28
2                  3                March        5276252.36
3                  4                April        5121722.76
4                  5                  May        5487660.59
5                  6                 June        5193359.82
6                  7                 July        5225688.25
7                  8               August        5532173.13
8                  9            September        5061384.53
9                 10              October        5377541.58
10                11             November        5089180.86
11                12             December        5422432.57

# 5. Customer Behavior Analysis

In [19]:
# Identify customers who placed more than 5 orders in a single month.
# Find customers whose average order value exceeds 1500.
# Identify customers who placed orders from multiple cities.
# Find repeat customers with more than one order.

# 6. Anomaly and Risk Indicators

In [20]:
# Identify orders where:
# Quantity is greater than 20
# Total_Amount is less than 100
# Find returned orders with Total_Amount > 2000.
# Detect customers who placed multiple orders on the same day.

# 7. Data Merging and Joining

# You are given another dataset named customer_details.csv with the following columns:

In [21]:
customer = pd.read_csv("customer_details.csv")
customer.head()

   Customer_ID  Age Gender Membership_Level
0         1001   58   Male           Silver
1         1002   35   Male           Silver
2         1003   65   Male             Gold
3         1004   52   Male             Gold
4         1005   20   Male           Silver

In [22]:
merged_data = pd.merge(data,customer,on="Customer_ID",how="outer")
merged_data.head()

,Order_ID,Customer_ID,Order_Date,Product,Category,Quantity,Unit_Price,Payment_Method,Order_Status,City,...,Order_Date_Day,Order_Date_Month,Order_Date_MonthName,Order_Date_Year,Discounted_Amount,Price_Level,Revenue_Per_Item,Age,Gender,Membership_Level
0,13681.0,1000,2024-08-05,Camera,Clothing,12.0,1566.34,Credit Card,Completed,Hyderabad,...,5.0,8.0,August,2024.0,16916.472,High,1566.34,NaN,NaN,NaN
1,21633.0,1000,2024-01-17,Headphones,Electronics,14.0,2302.04,UPI,Completed,Kolkata,...,17.0,1.0,January,2024.0,29005.704,High,2302.04,NaN,NaN,NaN
2,28653.0,1000,2023-06-23,Watch,Electronics,1.0,2455.73,UPI,Cancelled,Hyderabad,...,23.0,6.0,June,2023.0,2455.730,Medium,2455.73,NaN,NaN,NaN
3,36063.0,1000,2024-10-19,Camera,Home Appliances,24.0,1657.79,UPI,Completed,Pune,...,19.0,10.0,October,2024.0,35808.264,High,1657.79,NaN,NaN,NaN
4,40121.0,1000,2023-09-05,Tablet,Electronics,12.0,54.36,Credit Card,Completed,Mumbai,...,5.0,9.0,September,2023.0,652.320,Low,54.36,NaN,NaN,NaN

# 8. Visualization

In [23]:
# Visualize monthly revenue using a line chart.
# Create a bar chart for revenue by category.
# Plot the top 10 customers by total spending.